global:

  DATA_PATH: "./data/"
  ACCEPTED_FILES: 
    -".txt"
    -".html"
    -".pdf"

chains:

  base:

    #Roles that A2rchi knows about
    ROLES: 
      - User
      - A2rchi
      - Expert 

  chain: 

    #Pick one of the models listed in the model class map below
    MODEL_NAME: OpenAILLM 

    #Map of all the class models and their keyword arguments
    MODEL_CLASS_MAP:
      OpenAILLM: 
        class: OpenAILLM
        kwargs: 
          model_name: gpt-4
          temperature: 1
      DumbLLM:
        class: DumbLLM
        kwargs: 
      LlamaLLM:
        class: LlamaLLM
        kwargs:
          model_path: null 

utils: 

  mailbox: 
    IMAP4_PORT: 143